[package]
name = "fastcgi-server"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
edition = "2021"

authors = ["TheJokr <leo@bloecher.dev>"]
repository = "https://github.com/TheJokr/fastcgi-server"
description = "Yet another server-side FastCGI library"
keywords = ["fastcgi", "protocol", "backend", "web"]
categories = ["network-programming", "web-programming"]

[dependencies]
thiserror = "1.0"
bitflags = "2.0"
