name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: 41 14 * * 3
  pull_request:
  push:
    paths:
      - src/**
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always
  # Fail CI on any warnings
  RUSTFLAGS: "-Dwarnings"

jobs:
  test-stable:
    name: Test on Rust stable
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      # Runner's default (stable) rustc is fine
      - uses: Swatinem/rust-cache@v2

      - name: Run lints (Clippy)
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --all-features

  test-other:
    if: github.event_name == 'schedule'
    strategy:
      matrix:
        channel: [beta]
      fail-fast: false

    name: Test on Rust ${{ matrix.channel }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        run: rustup default ${{ matrix.channel }}
      - uses: Swatinem/rust-cache@v2

      - name: Run lints (Clippy)
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --all-features
