name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: 41 14 * * 3
  pull_request:
  push:
    paths:
      - src/**
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always
  # Fail CI on any warnings
  RUSTFLAGS: "-Dwarnings"

jobs:
  test-stable:
    name: Test on Rust stable
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      # Runner's default (stable) rustc is fine
      - uses: Swatinem/rust-cache@v2
      - name: Install SARIF tools
        run: cargo install clippy-sarif sarif-fmt

      - name: Run lints (Clippy)
        id: run-lint
        run: cargo clippy --all-targets --all-features --message-format json |
          clippy-sarif | tee clippy.sarif | sarif-fmt
      - uses: github/codeql-action/upload-sarif@v2
        if: contains(fromJSON('["success", "failure"]'), steps.run-lint.conclusion)
        with:
          sarif_file: clippy.sarif
          wait-for-processing: false

      - name: Run tests
        run: cargo test --all-features

  test-other:
    if: github.event_name == 'schedule'
    strategy:
      matrix:
        channel: [beta]
      fail-fast: false

    name: Test on Rust ${{ matrix.channel }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        run: rustup default ${{ matrix.channel }}
      - uses: Swatinem/rust-cache@v2

      - name: Run lints (Clippy)
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --all-features
